/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordmanagementia;

import java.awt.Color;
import java.util.Scanner;

/**
 *
 * @author imsoc
 */
public class menuForm extends javax.swing.JFrame {

    /**
     * Creates new form menuForm
     */
    public menuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        panelBorder1 = new swing.PanelBorder();
        jButtonViewEncrypted = new swing.MyButton();
        jButtonViewDecrypted = new swing.MyButton();
        jButtonAddPass = new swing.MyButton();
        jButtonEditPass = new swing.MyButton();
        jButtonLogout = new swing.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(246, 114, 69));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));

        jButtonViewEncrypted.setText("View Encrypted Passwords");
        jButtonViewEncrypted.setBorderColor(new java.awt.Color(0, 0, 0));
        jButtonViewEncrypted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonViewEncryptedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonViewEncryptedMouseExited(evt);
            }
        });
        jButtonViewEncrypted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewEncryptedActionPerformed(evt);
            }
        });
        panelBorder1.add(jButtonViewEncrypted);
        jButtonViewEncrypted.setBounds(390, 200, 210, 25);

        jButtonViewDecrypted.setText("View Decrypted Passwords");
        jButtonViewDecrypted.setBorderColor(new java.awt.Color(0, 0, 0));
        jButtonViewDecrypted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonViewDecryptedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonViewDecryptedMouseExited(evt);
            }
        });
        jButtonViewDecrypted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewDecryptedActionPerformed(evt);
            }
        });
        panelBorder1.add(jButtonViewDecrypted);
        jButtonViewDecrypted.setBounds(390, 240, 210, 25);

        jButtonAddPass.setText("Add New Password");
        jButtonAddPass.setBorderColor(new java.awt.Color(0, 0, 0));
        jButtonAddPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddPassMouseExited(evt);
            }
        });
        jButtonAddPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPassActionPerformed(evt);
            }
        });
        panelBorder1.add(jButtonAddPass);
        jButtonAddPass.setBounds(390, 280, 210, 25);

        jButtonEditPass.setText("Edit Stored Password");
        jButtonEditPass.setBorderColor(new java.awt.Color(0, 0, 0));
        jButtonEditPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditPassMouseExited(evt);
            }
        });
        jButtonEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPassActionPerformed(evt);
            }
        });
        panelBorder1.add(jButtonEditPass);
        jButtonEditPass.setBounds(390, 320, 210, 25);

        jButtonLogout.setText("Logout");
        jButtonLogout.setBorderColor(new java.awt.Color(0, 0, 0));
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        panelBorder1.add(jButtonLogout);
        jButtonLogout.setBounds(390, 360, 210, 25);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("What would you like to do?");
        panelBorder1.add(jLabel1);
        jLabel1.setBounds(370, 160, 250, 25);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewEncryptedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewEncryptedMouseEntered
        jButtonViewEncrypted.setBackground(new Color(255,188,111));
    }//GEN-LAST:event_jButtonViewEncryptedMouseEntered

    private void jButtonViewEncryptedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewEncryptedMouseExited
        jButtonViewEncrypted.setBackground(new Color(230,146,50));
    }//GEN-LAST:event_jButtonViewEncryptedMouseExited

    private void jButtonViewEncryptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewEncryptedActionPerformed
        viewPasswordForm viewPasswordForm = new viewPasswordForm();
        viewPasswordForm.setVisible(true); //opens viewPasswordForm
        viewPasswordForm.pack();
        viewPasswordForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonViewEncryptedActionPerformed

    private void jButtonViewDecryptedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewDecryptedMouseEntered
        jButtonViewDecrypted.setBackground(new Color(255,188,111));
    }//GEN-LAST:event_jButtonViewDecryptedMouseEntered

    private void jButtonViewDecryptedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewDecryptedMouseExited
        jButtonViewDecrypted.setBackground(new Color(230,146,50));
    }//GEN-LAST:event_jButtonViewDecryptedMouseExited

    private void jButtonViewDecryptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewDecryptedActionPerformed
        viewPasswordForm viewPasswordForm = new viewPasswordForm();
        viewPasswordForm.setVisible(true); //opens viewPasswordForm
        viewPasswordForm.pack();
        viewPasswordForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonViewDecryptedActionPerformed

    private void jButtonAddPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddPassMouseEntered
        jButtonAddPass.setBackground(new Color(255,188,111));
    }//GEN-LAST:event_jButtonAddPassMouseEntered

    private void jButtonAddPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddPassMouseExited
        jButtonAddPass.setBackground(new Color(230,146,50));
    }//GEN-LAST:event_jButtonAddPassMouseExited

    private void jButtonAddPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPassActionPerformed
        addPasswordForm addPasswordForm = new addPasswordForm();
        addPasswordForm.setVisible(true); //opens addPasswordForm
        addPasswordForm.pack();
        addPasswordForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonAddPassActionPerformed

    private void jButtonEditPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditPassMouseEntered
        jButtonEditPass.setBackground(new Color(255,188,111));
    }//GEN-LAST:event_jButtonEditPassMouseEntered

    private void jButtonEditPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditPassMouseExited
        jButtonEditPass.setBackground(new Color(230,146,50));
    }//GEN-LAST:event_jButtonEditPassMouseExited

    private void jButtonEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPassActionPerformed
        //setup for method to edit existing stored password
        editPasswordForm editPasswordForm = new editPasswordForm();
        editPasswordForm.setVisible(true); //opens editPasswordForm
        editPasswordForm.pack();
        editPasswordForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonEditPassActionPerformed

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
        jButtonLogout.setBackground(new Color(255,188,111));
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
        jButtonLogout.setBackground(new Color(230,146,50));
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyButton jButtonAddPass;
    private swing.MyButton jButtonEditPass;
    private swing.MyButton jButtonLogout;
    private swing.MyButton jButtonViewDecrypted;
    private swing.MyButton jButtonViewEncrypted;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
