/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordmanagementia;

import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class registerForm extends javax.swing.JFrame {
    public registerForm() {
        initComponents();
        this.setLocationRelativeTo(null); //centers panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonRegister = new swing.MyButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmailRegister = new javax.swing.JTextField();
        txtUserRegister = new javax.swing.JTextField();
        txtPass2Register = new javax.swing.JPasswordField();
        txtPass1Register = new javax.swing.JPasswordField();
        cmdOpenLogin = new javax.swing.JLabel();
        panelBorder1 = new swing.PanelBorder();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(86, 180, 211));
        kGradientPanel1.setkStartColor(new java.awt.Color(52, 143, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("Register");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Password:");

        jButtonRegister.setBackground(new java.awt.Color(86, 180, 211));
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("REGISTER");
        jButtonRegister.setBorderColor(new java.awt.Color(52, 143, 80));
        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseExited(evt);
            }
        });
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Retype Password:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Email:");

        txtEmailRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailRegister.setForeground(new java.awt.Color(153, 153, 153));
        txtEmailRegister.setText("email");
        txtEmailRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailRegisterFocusLost(evt);
            }
        });

        txtUserRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserRegister.setForeground(new java.awt.Color(153, 153, 153));
        txtUserRegister.setText("username");
        txtUserRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserRegisterFocusLost(evt);
            }
        });

        txtPass2Register.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass2Register.setForeground(new java.awt.Color(153, 153, 153));
        txtPass2Register.setText("password");
        txtPass2Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass2RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPass2RegisterFocusLost(evt);
            }
        });

        txtPass1Register.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass1Register.setForeground(new java.awt.Color(153, 153, 153));
        txtPass1Register.setText("password");
        txtPass1Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass1RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPass1RegisterFocusLost(evt);
            }
        });

        cmdOpenLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdOpenLogin.setForeground(new java.awt.Color(31, 197, 255));
        cmdOpenLogin.setText("Back to Login!");
        cmdOpenLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdOpenLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdOpenLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdOpenLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdOpenLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(258, 258, 258))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(258, 258, 258))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(226, 226, 226))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(258, 258, 258))
                    .addComponent(txtEmailRegister)
                    .addComponent(txtPass2Register)
                    .addComponent(txtPass1Register))
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(cmdOpenLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPass1Register, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPass2Register, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdOpenLogin)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(282, 282, 282)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(285, 285, 285)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        db j = new db();
        String userR = txtUserRegister.getText();
        String emailR = txtEmailRegister.getText();
        String passR1 = String.valueOf(txtPass1Register.getPassword());
        Random rnd = new Random();
        int random = 100000 + rnd.nextInt(900000);
        String secretKey = String.valueOf(random);
        String secretKeyUser = secretKey + userR;
        passR1 = aes.encrypt(passR1, secretKeyUser);//encrypt pass based on concated string
        
        if(verifyFields()){ //checks whether all fields are filled in and that pass1 and pass2 match
            if(j.uniqueUsername(userR)){ //checks database as to whether username is unique
                j.createAccount(userR, emailR, passR1, secretKey); //passes values into database
            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void txtUserRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserRegisterFocusGained
        //clear the textfield on focus if the text is "username"
        if(txtUserRegister.getText().trim().toLowerCase().equals("username")){
            txtUserRegister.setText("");
            txtUserRegister.setForeground(Color.black);
        } 
    }//GEN-LAST:event_txtUserRegisterFocusGained

    private void txtUserRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserRegisterFocusLost
        //when focus is lost and text is empty or "username", sets text to gray "username"
        if(txtUserRegister.getText().trim().equals("") || txtUserRegister.getText().trim().toLowerCase().equals("username")){
            txtUserRegister.setText("username");
            txtUserRegister.setForeground(new Color (153,153,153));
        }
    }//GEN-LAST:event_txtUserRegisterFocusLost

    private void txtEmailRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailRegisterFocusGained
        //clear the textfield on focus if the text is "email"
        if(txtEmailRegister.getText().trim().toLowerCase().equals("email")){
            txtEmailRegister.setText("");
            txtEmailRegister.setForeground(Color.black);
        } 
    }//GEN-LAST:event_txtEmailRegisterFocusGained

    private void txtEmailRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailRegisterFocusLost
        //when focus is lost and text is empty or "email", sets text to gray "email"
        if(txtEmailRegister.getText().trim().equals("") || txtEmailRegister.getText().trim().toLowerCase().equals("email")){
            txtEmailRegister.setText("email");
            txtEmailRegister.setForeground(new Color (153,153,153));
        }
    }//GEN-LAST:event_txtEmailRegisterFocusLost

    private void txtPass1RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1RegisterFocusGained
        //clear the textfield on focus if the text is "password"
        String pass = String.valueOf(txtPass1Register.getPassword()); //necessary as field is password field (hidden)
        if(pass.trim().toLowerCase().equals("password")){
            txtPass1Register.setText("");
            txtPass1Register.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPass1RegisterFocusGained

    private void txtPass1RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1RegisterFocusLost
        //when focus is lost and text is empty of "password", sets text to gray "password"
        String pass = String.valueOf(txtPass1Register.getPassword());
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            txtPass1Register.setText("password");
            txtPass1Register.setForeground(new Color (153,153,153));
        }
    }//GEN-LAST:event_txtPass1RegisterFocusLost

    private void txtPass2RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2RegisterFocusGained
        String pass = String.valueOf(txtPass2Register.getPassword());
        if(pass.trim().toLowerCase().equals("password")){
            txtPass2Register.setText("");
            txtPass2Register.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPass2RegisterFocusGained

    private void txtPass2RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2RegisterFocusLost
        String pass = String.valueOf(txtPass2Register.getPassword());
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            txtPass2Register.setText("password");
            txtPass2Register.setForeground(new Color (153,153,153));
        }
    }//GEN-LAST:event_txtPass2RegisterFocusLost

    private void jButtonRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseEntered
        jButtonRegister.setBackground(new Color(255,188,111));//sets jbutton background to light orange
    }//GEN-LAST:event_jButtonRegisterMouseEntered

    private void jButtonRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseExited
        jButtonRegister.setBackground(new Color(230,146,50)); //sets jbutton background to dark orange
    }//GEN-LAST:event_jButtonRegisterMouseExited

    private void cmdOpenLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdOpenLoginMouseEntered
        Border label_border = BorderFactory.createMatteBorder(0,0,2,0,new Color(255,188,111));//creates light orange underline on button when hovering
        cmdOpenLogin.setBorder(label_border);
    }//GEN-LAST:event_cmdOpenLoginMouseEntered

    private void cmdOpenLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdOpenLoginMouseExited
        cmdOpenLogin.setBorder(null); //no border on jbutton when not hovering over it
    }//GEN-LAST:event_cmdOpenLoginMouseExited

    private void cmdOpenLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdOpenLoginMouseClicked
        loginForm lf = new loginForm(); //opens login gui when clicked
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //default closing window
        this.dispose();
    }//GEN-LAST:event_cmdOpenLoginMouseClicked

    public boolean verifyFields(){
        String userR = txtUserRegister.getText();
        String emailR = txtEmailRegister.getText();
        String passR1 = String.valueOf(txtPass1Register.getPassword());
        String passR2 = String.valueOf(txtPass2Register.getPassword());
        
        if(userR.trim().equals("") || emailR.trim().equals("") || passR1.trim().equals("") || passR2.trim().equals("")
                || userR.trim().equals("username") || emailR.trim().equals("email") || passR1.trim().equals("password") || passR2.trim().equals("password")){
            //ensures all fields are full
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty");
            return false;
        }
        else if(!passR1.equals(passR2)){
            JOptionPane.showMessageDialog(null, "Passwords Don't Match", "Confirm Password",2);
            return false;
        }else{
            return true;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cmdOpenLogin;
    private swing.MyButton jButtonRegister;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private swing.PanelBorder panelBorder1;
    private javax.swing.JTextField txtEmailRegister;
    private javax.swing.JPasswordField txtPass1Register;
    private javax.swing.JPasswordField txtPass2Register;
    private javax.swing.JTextField txtUserRegister;
    // End of variables declaration//GEN-END:variables
}
